language: dart
dart:
  - dev
sudo: false
script: ./tool/travis.sh
env:
  # these do not run on cron jobs
  - LINTER_BOT=main
  - LINTER_BOT=benchmark
  - LINTER_BOT=pana_baseline
  - LINTER_BOT=release
  # this only runs on cron jobs
  - LINTER_BOT=fuzz

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
    - ./tool/fuzz.dart.snapshot.corpus
